version: "3.7"

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.8.0"
    environment:
      - "bootstrap.memory_lock=true"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms640m -Xmx640m"
      - "discovery.type=single-node"
      - "cluster.name=field.dainst.org"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - "./data/elasticsearch:/usr/share/elasticsearch/data"

  api:
    image: "dainst/idai-field-web-api"
    build: "./api"
    ports:
      - "4000:4000"
    volumes:
      - "./api/config:/opt/src/api/config"
      - "./api/resources:/opt/src/api/resources"
      - "./api/lib:/opt/src/api/lib"
      - "./api/test:/opt/src/api/test"
      - "./api/_build:/opt/src/api/_build"
      - "./api/images:/opt/src/api/images"

  ui:
    image: "dainst/idai-field-web-ui"
    build: "./ui"
    ports:
      - "3001:80"
    volumes:
      - "./ui/build:/usr/share/nginx/html"
