version: "3.7"

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.8.0"
    environment:
      - "bootstrap.memory_lock=true"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms640m -Xmx640m"
      - "discovery.type=single-node"
      - "cluster.name=field.dainst.org"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - "elasticsearch-data:/usr/share/elasticsearch/data"

  api:
    image: "dainst/idai-field-web-api:latest"
    ports:
      - "4000:4000"
    volumes:
      - "/opt/idai-field/api/config:/opt/src/api/config"
    networks:
      - web
      - default
    deploy:
      labels:
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:field.test.idai.world; PathPrefixStrip:/api"
        - "traefik.port=4000"

volumes:
  elasticsearch-data:

networks:
  web:
    external: true
